### ISSUE TITLE
Disentangle cookies and support panel functions

### ISSUE THREAD

**Issue by cjrace** [dfe-analytical-services/dfeshiny#21]
Currently the two sets of functions rely on variables being set from the other. Would be nice to allow the cookies module to have it's own tab or ui output that could be put anywhere rather than reliant on the support panel.

**Comment by jen-machin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix double printing issue with cookie consent statement](https://trello.com/c/uOGtQxKb/1352-fix-double-printing-issue-with-cookie-consent-statement)

**Comment by cjrace** [comment]
Fixed in #40
