### ISSUE TITLE
Fix styler errors on cookies.R script

### ISSUE THREAD

**Issue by cjrace** [dfe-analytical-services/dfeshiny#27]
Currently if you run either `styler::style_pkg()` or styler::style_file("R/cookies.R"). You get the following error:

![image](https://github.com/dfe-analytical-services/dfeshiny/assets/52536248/ca218760-2eef-4e1f-9f86-ae04574d100b)

We should work out what's happening and the best way to fix it.

**Comment by rmbielby** [comment]
Think this was fixed by PR #34
